### ISSUE TITLE
wsamjs error

### ISSUE THREAD

**Issue by DirosChen** [irgaly/kfswatch#88]
on build.gradle.kts
sourceSets {
        val desktopMain by getting
        
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation("io.github.irgaly.kfswatch:kfswatch:1.2.0")
        }
        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
        }
    }
not work in wasmjs 
:composeApp:wasmJsMain: Could not resolve io.github.irgaly.kfswatch:kfswatch:1.2.0.
Required by:
project :composeApp

**Comment by irgaly** [comment]
@DirosChen 

I just published kfswatch v1.3.0, this version supports Kotlin/Wasm (wasmJs - nodeJs target). Please check this one 😄 

https://github.com/irgaly/kfswatch/releases/tag/v1.3.0

---

* ref
    * #89

**Comment by DirosChen** [comment]
ok thanks
